Repository aaronto0705/Tempo, pull requests merged in 2024-04, with the labels that each got.

#15 Github Actions
  .eslintignore
  .eslintrc.json
  .github/workflows/eslint.yml
  .github/workflows/npm-check.yml
  .github/workflows/tests.yml
  App.js
  package-lock.json
  package.json
Labels: task

#13 Landing page
  README.md
  landing-page/.gitignore
  landing-page/README.md
  landing-page/package-lock.json
  landing-page/package.json
  landing-page/public/favicon.ico
  landing-page/public/index.html
  landing-page/public/logo192.png
  landing-page/public/logo512.png
  landing-page/public/manifest.json
  landing-page/public/robots.txt
  landing-page/public/tempo_logo.png
  landing-page/src/App.css
  landing-page/src/App.js
  landing-page/src/App.test.js
  landing-page/src/index.css
  landing-page/src/index.js
  landing-page/src/logo.svg
  landing-page/src/reportWebVitals.js
  landing-page/src/setupTests.js
Labels: task

#25 Extracting User Data
  App.js
  landing-page/build/asset-manifest.json
  landing-page/build/favicon.ico
  landing-page/build/index.html
  landing-page/build/logo192.png
  landing-page/build/logo512.png
  landing-page/build/manifest.json
  landing-page/build/robots.txt
  landing-page/build/static/css/main.f855e6bc.css
  landing-page/build/static/css/main.f855e6bc.css.map
  landing-page/build/static/js/453.7ee4257d.chunk.js
  landing-page/build/static/js/453.7ee4257d.chunk.js.map
  landing-page/build/static/js/main.50ee23c3.js
  landing-page/build/static/js/main.50ee23c3.js.LICENSE.txt
  landing-page/build/static/js/main.50ee23c3.js.map
  landing-page/build/tempo_logo.png
  landing-page/package.json
  package-lock.json
  package.json
  screens/Credentials.js
  screens/Home.js
  screens/LoginScreen.js
  screens/SpotifyAuth.js
Labels: bug, enhancement

#32 Save user data to Firebase
  database.rules.json
  firestore.rules
  package-lock.json
  package.json
  screens/Credentials.js
  screens/Home.js
  screens/LoginScreen.js
  storage.rules
Labels: bug, enhancement

#34 Stream songs 2
  App.js
  StackNavigator.js
  package-lock.json
  package.json
  screens/Credentials.js
  screens/Home.js
  screens/Preference4.js
  screens/Songs.js
Labels: feature

#38 Fixes inability to add song issue
  README.md
  package-lock.json
  screens/Preference4.js
Labels: bug

#36 WIP: Adding songs based on changing pace
  PR
  package-lock.json
  screens/Credentials.js
  screens/Preference4.js
  screens/SpotifyAuth.js
Labels: feature
